spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: /Users/tarsila.samille/Downloads/distribuida spring/config-server/.git/
          default-label: main
server:
  port: 8888