spring:
  application:
    name: service-gateway-API
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
#      default-filters:
#        - name: Retry
#          args:
#            retries: 3
#            methods: GET
#            series: SERVER_ERROR
#            exceptions: java.io.IOException
#            backoff:
#              firstBackoff: 50ms
#              maxBackOff: 500ms
#              factor: 2
#              basedOnPreviousValue: false
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
